[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "maze_nca"
version = "0.1.0"
description = "Neural Cellular Automata Maze Project"
requires-python = ">=3.12"
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]